openapi: 3.0.3
info:
  title: AuditEvent Service (Render)
  description: |
    **Prereqisites**:</br>
    -
    The Health Record System shall provide 
    - name
    - role ((profession-)oid)
    - identifier (telematik-id or kvnr)
    - indication of a valid entitlement 
    of the current user (requestor) for evaluation in operations.

    Operations mandating a valid entitlement implicitely mandate use of a VAU-channel
    and a valid ID-Token. If one of these conditions is not met, then the response
    of the (aborted) operation shall always be '403': 'notEntitled'. 

    **Retry interval**:</br>
    -
    The following retry intervals are suggested in case of an error response:<br>
    - '409' Conflict (statusMismatch).
      - approx. 24 hours
    - '500' Internal Error
      - approx. 10 minutes

    **User Agent**:</br>
    -
    The user agent information (x-useragent) is part of any request, even if 
    not essentially required for the operation (e.g. raw-data collection), and
    may be considered for provider internal use. 

  contact:
    name: gematik GmbH
    url: 'https://www.gematik.de'

  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

  version: 0.0.1

servers:
- url: https://www.example.com/api

tags:
- name: PDF/A
  description: Signed PDF/A File



paths:
  /audit/v1/render/pdf:
    parameters:
      - $ref: '#/components/parameters/useragent' 
    get:
      tags:
      - PDF/A
      operationId: renderAuditEventsToPDF
      summary: "Returns a signed PDF/A file of all AuditEvents in a human-readable format."
      description: |
        The AuditEvent Service **SHALL** return the list of all AuditEvent entries as a signed PDF/A file. 
        The signature key **SHALL** correspond to the issuer identity ID.FD.SIG. The associated certificate C.FD.SIG contains the role "oid_epa_logging".

        
        **Allowed user groups [professionOID]**
        -
        - oid_versicherter

        **Error Handling**
        -
        | Conditions | Status code | Error code | Remarks |
        |------------|-------------|------------|---------|
        | Successful operation | 200 |||
        | Requestor has no valid entitlement | 403 | notEntitled ||
        | Requestor role is not in the list of allowed usergroups | 403 | invalidOid ||
        | Health record is not in state ACTIVATED | 409 | statusMismatch | (see 'Retry interval') |
        | Any other error | 500 | internalError | (see 'Retry interval') |

      parameters:
        - $ref: '#/components/parameters/insurantid'
        - $ref: '#/components/parameters/useragent'
      responses:
        "200":
          description: Success
          content:
            application/pdf:
              schema:
                type: string
                format: byte
              example: Signed PDF/A File
        '403':
          $ref: '#/components/responses/Error403Forbidden'
        '409':
          $ref: '#/components/responses/Error409Conflict'
        '500':
          $ref: '#/components/responses/Error500InternalError'


components:
  responses:
    Error403Forbidden:
      description: Forbidden.
      content:
        application/json:
          examples:
            notEntitled:
              summary: Requestor has no valid entitlement
              value:
                errorCode: notEntitled
            invalidOid:
              summary: Requestor role is not in the list of allowed usergroups
              value:
                errorCode: invalidOid

          schema:
            $ref: '#/components/schemas/ErrorType'
    Error409Conflict:
      description: Conflict.
      content:
        application/json:
          example:
            errorCode: statusMismatch
          schema:
            $ref: '#/components/schemas/ErrorType'
    Error500InternalError:
      description: Internal Server Error
      content:
        application/json:
          example:
            errorCode: internalError
          schema:
            $ref: '#/components/schemas/ErrorType'

  parameters:
    insurantid:
      name: x-insurantid
      in: header
      description: Health Record Identifier.
      required: true
      schema:
        $ref: '#/components/schemas/InsurantIdType'
    useragent:
      name: x-useragent
      in: header
      description: user agent information
      required: true
      schema:
        $ref: '#/components/schemas/UserAgentType'

  schemas:
    InsurantIdType:
      type: string
      description: |-
        The health record identifier. 
        For today the record identifier equals the insurant id (kvnr). The record identifier does not include any homeCommunity identification.
      pattern: '^[A-Z]{1}\d{9}$'
      example: Z123456789
    UserAgentType:
      type: string
      pattern: '[a-zA-Z0-9_\-\+\.: \(\)]{1,20}\/[a-zA-Z0-9_\-\+\.: \(\)]{1,23}\/[a-zA-Z0-9_\-\+\.: \(\)]{1,20}'
      description: Information about client software.
      example: "Softwareprodukt XYZ/2.4.6/Hersteller ABC"
    ErrorType:
      description: Error object with additional information about the occurred error
      type: object
      properties:
        errorCode:
          description: Error condition specifier
          type: string
        errorDetail:
          description: Additional details regarding the error condition (if applicable)
          type: string
      required:
        - errorCode
